version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # AWS ECR 로그인
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 416225317325.dkr.ecr.us-east-2.amazonaws.com

      # [수정됨] 뒤에 :latest 제거함
      - REPOSITORY_URI=416225317325.dkr.ecr.us-east-2.amazonaws.com/aivle-bookservice-team5-backend

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - chmod +x gradlew

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Java application...
      - ./gradlew clean build -x test

      - echo Building the Docker image...
      # 여기서 :latest가 붙으므로 위 변수에서 제거한 것임
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      # [주의] "my-web-container"를 실제 ECS 작업 정의의 컨테이너 이름으로 변경했는지 꼭 확인하세요!
      - printf '[{"name":"my-web-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - k8s/**/*